version: "3.9"

services:
  portfolio-service:
    build: .
    container_name: portfolio-id-service
    env_file:
      - .env
    ports:
      - "8095:8095"
    restart: unless-stopped
    networks:
      - pms-network

networks:
  pms-network:
    external: true
