version: "3.9"

services:
  portfolio-id-generator:
    build: .
    container_name: portfolio-id-generator
    ports:
      - "8095:8095"
    environment:
      SERVER_PORT: 8095

      DB_URL: jdbc:postgresql://db-instance-pms.cvk4yqey0ex7.us-east-2.rds.amazonaws.com:5432/pms_portfolio_db
      DB_USERNAME: postgres
      DB_PASSWORD: PMS.2025
    networks:
      - portfolio-net

networks:
  portfolio-net:
