server:
  port: ${SERVER_PORT:8095}

spring:
  application:
    name: portfolioId-generator

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${DB_SHOW_SQL}
    properties:
      hibernate:
        dialect: ${DB_DIALECT}

logging:
  level:
    org.hibernate.SQL: DEBUG
    root: INFO
    com.example.portfolioId.generator: DEBUG
